import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="containerInicial">
          <header className="bg-principalColor">
            <NavBar />
          </header>
          <main>
            {children}
          </main>
          <footer className="bg-principalColor">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
